on:
  push:
    tags:
      - '*'
  workflow_dispatch:

name: Publish observation-tools crate
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rust
        run: rustup install stable
      - name: Publish
        run: cargo publish -p observation-tools --token "$CARGO_REGISTRY_TOKEN"
        env:
          CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
 